# Generated by Django 5.1.5 on 2025-01-21 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('total_supply', models.IntegerField(default=20000000)),
                ('decimals', models.IntegerField(default=18)),
                ('network', models.CharField(choices=[('Binance', 'Binance Smart Chain'), ('Ethereum', 'Ethereum'), ('Solana', 'Solana')], max_length=100)),
                ('contract_standard', models.CharField(default='ERC20', max_length=100)),
                ('liquidity_allocation', models.IntegerField(default=100)),
                ('staking_rewards', models.IntegerField(default=100)),
                ('governance_mechanism', models.CharField(default='DAO', max_length=100)),
                ('transaction_fees', models.IntegerField(default=100)),
                ('burn_mechanism', models.CharField(default='Deflationary', max_length=100)),
                ('deflationary_or_inflationary', models.CharField(default='Deflationary', max_length=100)),
                ('team_marketing_allocation', models.IntegerField(default=100)),
                ('vesting_schedules', models.CharField(default='Yes', max_length=100)),
                ('utility_use_cases', models.CharField(default='Yes', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.chat')),
            ],
        ),
    ]
