# Generated by Django 5.1.5 on 2025-01-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenparams',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interface.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tokenparams',
            name='network',
            field=models.CharField(choices=[('binance', 'Binance Smart Chain'), ('ethereum', 'Ethereum'), ('solana', 'Solana')], max_length=100),
        ),
    ]
