# Generated by Django 5.1.5 on 2025-01-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_tokenparams_chat_alter_message_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
                ('transaction_hash', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.chat')),
                ('token_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tokenparams')),
            ],
        ),
    ]
